services :
   - type : web
     name : filmigobot
     runtime : go
     repo : https://github.com/Jisin0/filmigobot.git
     buildCommand: go build .
     startCommand: ./filmigobot
     envVars :
       - key : BOT_TOKEN
         value : your-bots-token
       - key : DEFAULT_SEARCH_METHOD
         value: jw
       - key : PORT
         value : 10000